echo "Fetching all repositories..."

# Fetch the repositories from the GitHub API
RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/user/repos?per_page=100)

# Output the response for debugging (optional)
echo "API Response: $RESPONSE"

# Ensure 'fork' is properly handled and repositories are selected correctly
REPOS=$(echo "$RESPONSE" | jq -r '.[] | select(.fork == true) | .name')

# Debug the REPOS value
echo "Repositories to sync: $REPOS"

# Export the REPOS variable to GitHub Actions environment
echo "REPOS=$REPOS" >> $GITHUB_ENV
